name = "Evaluation"
uuid = "297065ec-f596-4b61-a215-5355053457d6"
authors = ["aclav Macha <vaclav.macha92@gmail.com>"]
version = "0.1.0"

[deps]
AccuracyAtTop = "99d982fd-5277-407e-85b7-ffc618e6d0f5"
AccuracyAtTopPrimal = "fe3dcc9b-297f-427f-9453-e9e3c6e3e222"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ClassificationAtTopDual = "655c3ecf-4336-4e22-841c-47f554d60d87"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EfficientNet = "8ae15c95-d670-4eca-a723-7364633ab054"
EvalMetrics = "251d5f9e-10c1-4699-ba24-e0ad168fa3e4"
Experiments = "0ed54c3c-39b1-4574-89de-30629e1c012c"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CSV = "0.10"
DataFrames = "1.3"
Distributions = "0.25"
EvalMetrics = "0.2"
Measurements = "2.7"
Plots = "1.31"
ProgressMeter = "1.7"
Reexport = "1.2"
StatsBase = "0.33"
